### ISSUE TITLE
Scss Color

### ISSUE THREAD

**Issue by ugurakcora** [sinanaslaan/country-list#1]
Scss'de color diye bir sayfa oluştur ve burada kullanacağın renkleri yaz.
Daha sonra kullanmak istediğin yerlerde bunu kullan.

örneğin colors.scss'e şöyle değişkenler ekleyip kullanmak istediğin yerlerde çağırabilirsin:
`$primary-color: #3498db;
$secondary-color: #2ecc71;
$background-color: #ecf0f1;
$text-color: #2c3e50;`

**Comment by sinanaslaan** [comment]
Tamamdır, eklendi.
