### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by ugurakcora** [sinanaslaan/country-list#3]
Sayfayı açtığımda direkt dark mode ile karşılaşıyorum. White mode'u seçtikten sonra sayfayı yeniliyorum dark mode geliyor. Seçtiğimi local storage'da tutmasını istiyorum.

**Comment by sinanaslaan** [comment]
tasarım olarak ilk dark mode geldiği için ilk dark mode'u yapmıştım. o yüzden default olarak dark mode geliyor. light mode eklemesini tamamladım. tercihlerin localstorage'de tutulması sağlandı.
